/**
 * Canonical entity vocabulary. Keep this module data-only so consumers can
 * inspect the registry without loading validation logic.
 *
 * Names match the Java Edition 1.21 entity registry ids exactly, so a
 * consumer bridging against `./vehicle` (boat, minecart) or `./projectile`
 * (arrow) can compare literals rather than maintain its own mapping.
 */

export const ENTITY_TYPES = [
  // Player
  'player',

  // Passive mobs
  'allay',
  'armadillo',
  'axolotl',
  'bat',
  'camel',
  'cat',
  'chicken',
  'cod',
  'cow',
  'dolphin',
  'donkey',
  'fox',
  'frog',
  'glow_squid',
  'horse',
  'mooshroom',
  'mule',
  'ocelot',
  'parrot',
  'pig',
  'pufferfish',
  'rabbit',
  'salmon',
  'sheep',
  'skeleton_horse',
  'sniffer',
  'squid',
  'strider',
  'tadpole',
  'tropical_fish',
  'turtle',
  'villager',
  'wandering_trader',
  'zombie_horse',

  // Neutral mobs
  'bee',
  'cave_spider',
  'enderman',
  'goat',
  'iron_golem',
  'llama',
  'trader_llama',
  'panda',
  'piglin',
  'polar_bear',
  'snow_golem',
  'spider',
  'wolf',
  'zombified_piglin',

  // Hostile mobs
  'blaze',
  'bogged',
  'breeze',
  'creeper',
  'drowned',
  'elder_guardian',
  'endermite',
  'evoker',
  'ghast',
  'giant',
  'guardian',
  'hoglin',
  'husk',
  'magma_cube',
  'phantom',
  'piglin_brute',
  'pillager',
  'ravager',
  'shulker',
  'silverfish',
  'skeleton',
  'slime',
  'stray',
  'vex',
  'vindicator',
  'warden',
  'witch',
  'wither_skeleton',
  'zoglin',
  'zombie',
  'zombie_villager',

  // Bosses
  'ender_dragon',
  'wither',

  // Projectiles
  'arrow',
  'breeze_wind_charge',
  'dragon_fireball',
  'egg',
  'ender_pearl',
  'experience_bottle',
  'fireball',
  'firework_rocket',
  'fishing_bobber',
  'llama_spit',
  'potion',
  'shulker_bullet',
  'small_fireball',
  'snowball',
  'spectral_arrow',
  'trident',
  'wind_charge',
  'wither_skull',

  // Vehicles
  'boat',
  'chest_boat',
  'chest_minecart',
  'command_block_minecart',
  'furnace_minecart',
  'hopper_minecart',
  'minecart',
  'spawner_minecart',
  'tnt_minecart',

  // Display and marker entities
  'block_display',
  'interaction',
  'item_display',
  'marker',
  'text_display',

  // Miscellaneous
  'area_effect_cloud',
  'armor_stand',
  'end_crystal',
  'evoker_fangs',
  'experience_orb',
  'eye_of_ender',
  'falling_block',
  'glow_item_frame',
  'item',
  'item_frame',
  'leash_knot',
  'lightning_bolt',
  'painting',
  'tnt',
] as const
