/**
 * Crafting recipes backed by the kernel's closed item vocabulary.
 *
 * This table contains the vanilla crafting rows currently represented by the
 * package. Recipe matching and inventory mutation remain separate concerns.
 */
import { itemStack } from './item-stack.js'
import {
  shapedRecipe,
  shapelessRecipe,
  type RecipeOptions,
  type RecipeTable,
} from './recipe-data.js'

const CRAFTING_TABLE_OPTIONS: RecipeOptions = { tags: ['crafting_table'] }

export const VANILLA_CRAFTING_RECIPES: RecipeTable = [
  shapelessRecipe('minecraft:bone-meal', ['bone'], itemStack('bone_meal', 3), CRAFTING_TABLE_OPTIONS),
  shapelessRecipe('minecraft:oak-planks', ['oak_log'], itemStack('oak_planks', 4), CRAFTING_TABLE_OPTIONS),
  shapedRecipe('minecraft:stick', ['P', 'P'], { P: 'oak_planks' }, itemStack('stick', 4), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:crafting-table',
    ['PP', 'PP'],
    { P: 'oak_planks' },
    itemStack('crafting_table', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:furnace',
    ['CCC', 'C C', 'CCC'],
    { C: 'cobblestone' },
    itemStack('furnace', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:chest',
    ['PPP', 'P P', 'PPP'],
    { P: 'oak_planks' },
    itemStack('chest', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe('minecraft:torch', ['C', 'S'], { C: 'coal', S: 'stick' }, itemStack('torch', 4), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:bucket',
    ['I I', ' I '],
    { I: 'iron_ingot' },
    itemStack('bucket', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:bow',
    [' ST', 'S T', ' ST'],
    { S: 'stick', T: 'string' },
    itemStack('bow', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe('minecraft:glowstone', ['DD', 'DD'], { D: 'glowstone_dust' }, itemStack('glowstone', 1), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:flint-and-steel',
    ['I ', ' F'],
    { I: 'iron_ingot', F: 'flint' },
    itemStack('flint_and_steel', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe(
    'minecraft:fire-charge',
    ['gunpowder', 'blaze_powder', 'coal'],
    itemStack('fire_charge', 3),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe(
    'minecraft:eye-of-ender',
    ['ender_pearl', 'blaze_powder'],
    itemStack('eye_of_ender', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:coal-block',
    ['CCC', 'CCC', 'CCC'],
    { C: 'coal' },
    itemStack('coal_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:coal-from-block', ['coal_block'], itemStack('coal', 9), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:iron-block',
    ['III', 'III', 'III'],
    { I: 'iron_ingot' },
    itemStack('iron_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:iron-from-block', ['iron_block'], itemStack('iron_ingot', 9), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:diamond-block',
    ['DDD', 'DDD', 'DDD'],
    { D: 'diamond' },
    itemStack('diamond_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:diamond-from-block', ['diamond_block'], itemStack('diamond', 9), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:redstone-block',
    ['RRR', 'RRR', 'RRR'],
    { R: 'redstone_dust' },
    itemStack('redstone_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:redstone-from-block', ['redstone_block'], itemStack('redstone_dust', 9), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:lapis-block',
    ['LLL', 'LLL', 'LLL'],
    { L: 'lapis_lazuli' },
    itemStack('lapis_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:lapis-from-block', ['lapis_block'], itemStack('lapis_lazuli', 9), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:emerald-block',
    ['EEE', 'EEE', 'EEE'],
    { E: 'emerald' },
    itemStack('emerald_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:emerald-from-block', ['emerald_block'], itemStack('emerald', 9), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:amethyst-block',
    ['AA', 'AA'],
    { A: 'amethyst_shard' },
    itemStack('amethyst_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe('minecraft:amethyst-from-block', ['amethyst_block'], itemStack('amethyst_shard', 4), CRAFTING_TABLE_OPTIONS),
  shapedRecipe('minecraft:sandstone', ['SS', 'SS'], { S: 'sand' }, itemStack('sandstone', 1), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:redstone-torch',
    ['R', 'S'],
    { R: 'redstone_dust', S: 'stick' },
    itemStack('redstone_torch', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:lever',
    ['S', 'C'],
    { S: 'stick', C: 'cobblestone' },
    itemStack('lever', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe('minecraft:stone-button', ['C'], { C: 'stone' }, itemStack('stone_button', 1), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:repeater',
    ['T T', ' R ', 'CCC'],
    { T: 'redstone_torch', R: 'redstone_dust', C: 'stone' },
    itemStack('repeater', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:redstone-lamp',
    [' R ', 'RGR', ' R '],
    { R: 'redstone_dust', G: 'glowstone' },
    itemStack('redstone_lamp', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:piston',
    ['PPP', 'CIC', 'CRC'],
    { P: 'oak_planks', C: 'cobblestone', I: 'iron_ingot', R: 'redstone_dust' },
    itemStack('piston', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:dispenser',
    ['CCC', 'CBC', 'CRC'],
    { C: 'cobblestone', B: 'bow', R: 'redstone_dust' },
    itemStack('dispenser', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:dropper',
    ['CCC', 'C C', 'CRC'],
    { C: 'cobblestone', R: 'redstone_dust' },
    itemStack('dropper', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:hopper',
    ['I I', 'ICI', ' I '],
    { I: 'iron_ingot', C: 'chest' },
    itemStack('hopper', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:end-stone-bricks',
    ['EE', 'EE'],
    { E: 'end_stone' },
    itemStack('end_stone_bricks', 4),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:end-crystal',
    ['GGG', 'GHG', 'GEG'],
    { G: 'glass', H: 'ghast_tear', E: 'eye_of_ender' },
    itemStack('end_crystal', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:ender-chest',
    ['OOO', 'OEO', 'OOO'],
    { O: 'obsidian', E: 'eye_of_ender' },
    itemStack('ender_chest', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:purpur-pillar',
    ['P', 'P'],
    { P: 'purpur_block' },
    itemStack('purpur_pillar', 2),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe('minecraft:purpur-slab', ['PPP'], { P: 'purpur_block' }, itemStack('purpur_slab', 6), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:purpur-stairs',
    ['P  ', 'PP ', 'PPP'],
    { P: 'purpur_block' },
    itemStack('purpur_stairs', 4),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:door',
    ['PP', 'PP', 'PP'],
    { P: 'oak_planks' },
    itemStack('door', 3),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:oak-stairs',
    ['P  ', 'PP ', 'PPP'],
    { P: 'oak_planks' },
    itemStack('oak_stairs', 4),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:anvil',
    ['BBB', ' I ', 'III'],
    { B: 'iron_block', I: 'iron_ingot' },
    itemStack('anvil', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:cauldron',
    ['I I', 'I I', 'III'],
    { I: 'iron_ingot' },
    itemStack('cauldron', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:bed',
    ['WWW', 'PPP'],
    { W: 'wool', P: 'oak_planks' },
    itemStack('bed', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:tnt',
    ['GSG', 'SGS', 'GSG'],
    { G: 'gunpowder', S: 'sand' },
    itemStack('tnt', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:ladder',
    ['S S', 'SSS', 'S S'],
    { S: 'stick' },
    itemStack('ladder', 3),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:rail',
    ['I I', 'ISI', 'I I'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('rail', 16),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:pressure-plate',
    ['PP'],
    { P: 'oak_planks' },
    itemStack('pressure_plate', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe('minecraft:stone-slab', ['CCC'], { C: 'stone' }, itemStack('stone_slab', 6), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:bowl',
    ['P P', ' P '],
    { P: 'oak_planks' },
    itemStack('bowl', 4),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:oak-boat',
    ['P P', 'PPP'],
    { P: 'oak_planks' },
    itemStack('oak_boat', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:minecart',
    ['I I', 'III'],
    { I: 'iron_ingot' },
    itemStack('minecart', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:fishing-rod',
    ['  S', ' ST', 'S T'],
    { S: 'stick', T: 'string' },
    itemStack('fishing_rod', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:shears',
    ['I ', ' I'],
    { I: 'iron_ingot' },
    itemStack('shears', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe('minecraft:wool', ['TT', 'TT'], { T: 'string' }, itemStack('wool', 1), CRAFTING_TABLE_OPTIONS),
  shapelessRecipe('minecraft:sugar', ['sugar_cane'], itemStack('sugar', 1), CRAFTING_TABLE_OPTIONS),
  shapedRecipe(
    'minecraft:wooden-pickaxe',
    ['PPP', ' S ', ' S '],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_pickaxe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:stone-pickaxe',
    ['CCC', ' S ', ' S '],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_pickaxe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-pickaxe',
    ['III', ' S ', ' S '],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_pickaxe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-pickaxe',
    ['DDD', ' S ', ' S '],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_pickaxe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:wooden-hoe',
    ['PP', ' S', ' S'],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_hoe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:stone-hoe',
    ['CC', ' S', ' S'],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_hoe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-hoe',
    ['II', ' S', ' S'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_hoe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-hoe',
    ['DD', ' S', ' S'],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_hoe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:wooden-sword',
    ['P', 'P', 'S'],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_sword', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:stone-sword',
    ['C', 'C', 'S'],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_sword', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-sword',
    ['I', 'I', 'S'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_sword', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-sword',
    ['D', 'D', 'S'],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_sword', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-helmet',
    ['III', 'I I'],
    { I: 'iron_ingot' },
    itemStack('iron_helmet', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-chestplate',
    ['I I', 'III', 'III'],
    { I: 'iron_ingot' },
    itemStack('iron_chestplate', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-leggings',
    ['III', 'I I', 'I I'],
    { I: 'iron_ingot' },
    itemStack('iron_leggings', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-boots',
    ['I I', 'I I'],
    { I: 'iron_ingot' },
    itemStack('iron_boots', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:gold-block',
    ['GGG', 'GGG', 'GGG'],
    { G: 'gold_ingot' },
    itemStack('gold_block', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe(
    'minecraft:gold-ingot',
    ['gold_block'],
    itemStack('gold_ingot', 9),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:wooden-shovel',
    ['P', 'S', 'S'],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_shovel', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:stone-shovel',
    ['C', 'S', 'S'],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_shovel', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-shovel',
    ['I', 'S', 'S'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_shovel', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-shovel',
    ['D', 'S', 'S'],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_shovel', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:gold-shovel',
    ['G', 'S', 'S'],
    { G: 'gold_ingot', S: 'stick' },
    itemStack('gold_shovel', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:wooden-axe',
    ['PP', 'PS', ' S'],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_axe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:stone-axe',
    ['CC', 'CS', ' S'],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_axe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:iron-axe',
    ['II', 'IS', ' S'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_axe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-axe',
    ['DD', 'DS', ' S'],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_axe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:gold-axe',
    ['GG', 'GS', ' S'],
    { G: 'gold_ingot', S: 'stick' },
    itemStack('gold_axe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:gold-pickaxe',
    ['GGG', ' S ', ' S '],
    { G: 'gold_ingot', S: 'stick' },
    itemStack('gold_pickaxe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:gold-hoe',
    ['GG', ' S', ' S'],
    { G: 'gold_ingot', S: 'stick' },
    itemStack('gold_hoe', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:gold-sword',
    ['G', 'G', 'S'],
    { G: 'gold_ingot', S: 'stick' },
    itemStack('gold_sword', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-helmet',
    ['DDD', 'D D'],
    { D: 'diamond' },
    itemStack('diamond_helmet', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-chestplate',
    ['D D', 'DDD', 'DDD'],
    { D: 'diamond' },
    itemStack('diamond_chestplate', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-leggings',
    ['DDD', 'D D', 'D D'],
    { D: 'diamond' },
    itemStack('diamond_leggings', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:diamond-boots',
    ['D D', 'D D'],
    { D: 'diamond' },
    itemStack('diamond_boots', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:paper',
    ['SSS'],
    { S: 'sugar_cane' },
    itemStack('paper', 3),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:book',
    ['PP', 'PL'],
    { P: 'paper', L: 'leather' },
    itemStack('book', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:enchanting-table',
    [' B ', 'DOD', 'OOO'],
    { B: 'book', D: 'diamond', O: 'obsidian' },
    itemStack('enchanting_table', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapelessRecipe(
    'minecraft:netherite-ingot',
    [
      'netherite_scrap',
      'netherite_scrap',
      'netherite_scrap',
      'netherite_scrap',
      'gold_ingot',
      'gold_ingot',
      'gold_ingot',
      'gold_ingot',
    ],
    itemStack('netherite_ingot', 1),
    CRAFTING_TABLE_OPTIONS,
  ),
  shapedRecipe(
    'minecraft:netherite-upgrade-smithing-template',
    ['DND', 'DTD', 'DDD'],
    { D: 'diamond', N: 'netherrack', T: 'netherite_upgrade_smithing_template' },
    itemStack('netherite_upgrade_smithing_template', 2),
    CRAFTING_TABLE_OPTIONS,
  ),
]
