export {
  MAX_RECIPE_SIDE,
  cellAt,
  craftGrid,
  anyOf,
  craftingIngredient,
  exactly,
  ingredientMatches,
  isAnyOfIngredient,
  isCraftingIngredient,
  isCraftingIngredientInput,
  shapelessRecipe,
  shapedRecipe,
  tagged,
} from "./recipe-data.js";
export type {
  CraftGrid,
  CraftGridInput,
  AnyOfIngredient,
  CraftingIngredient,
  CraftingIngredientInput,
  ExactIngredient,
  Ingredient,
  IngredientInput,
  ItemTagIngredient,
  ItemTagMemberships,
  PatternCell,
  Recipe,
  RecipeCategory,
  RecipeId,
  RecipeItemTag,
  RecipeMatchContext,
  RecipeOptions,
  RecipePattern,
  RecipeStationTag,
  RecipeTable,
  ShapedRecipe,
  ShapelessRecipe,
} from "./recipe-data.js";
export {
  conflictsIn,
  matchRecipe,
  matchRecipeWithAssignments,
  matchesRecipe,
  matchesShaped,
  matchesShapeless,
} from "./recipe-matching.js";
export type {
  RecipeConflict,
  RecipeConflictReason,
  RecipeIngredientAssignment,
  RecipeMatch,
  RecipeMatchWithAssignments,
} from "./recipe-matching.js";
export { VANILLA_CRAFTING_RECIPES } from "./recipe-vanilla-data.js";
