import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import * as Either from 'effect/Either'
import * as Schema from 'effect/Schema'

const record = Schema.Record({ key: Schema.String, value: Schema.Unknown })
const strings = Schema.Array(Schema.String)
const parse = (text: string): unknown => JSON.parse(text)
const read = async <A, I>(file: string, schema: Schema.Schema<A, I>): Promise<A> => {
  const result = Schema.decodeUnknownEither(schema)(parse(await readFile(file, 'utf8')))
  if (Either.isLeft(result)) throw new Error(`invalid golden ${file}: ${String(result.left)}`)
  return result.right
}

const golden = join(process.cwd(), 'test', 'golden')
const biome = await read(join(golden, 'vanilla-biome.json'), record)
const damage = await read(join(golden, 'vanilla-damage-type.json'), strings)
const effects = await read(join(golden, 'vanilla-mob-effect.json'), strings)
const enchantments = await read(join(golden, 'vanilla-enchantment.json'), record)
const tags = await read(join(golden, 'vanilla-tag.json'), record)

const climate = Object.fromEntries(Object.entries(biome).map(([file, value]) => {
  if (typeof value !== 'object' || value === null || !('temperature' in value) || !('downfall' in value) ||
      typeof value.temperature !== 'number' || typeof value.downfall !== 'number' ||
      !('has_precipitation' in value) || typeof value.has_precipitation !== 'boolean') {
    throw new Error(`biome climate is missing in ${file}`)
  }
  return [file.split('/').pop()?.replace('.json', '') ?? file, {
    temperature: value.temperature,
    downfall: value.downfall,
    hasPrecipitation: value.has_precipitation,
  }]
}))

const maxLevels = Object.fromEntries(Object.entries(enchantments).map(([id, value]) => {
  if (typeof value !== 'object' || value === null || !('max_level' in value) || typeof value.max_level !== 'number') {
    throw new Error(`enchantment max_level is missing in ${id}`)
  }
  return [id, value.max_level]
}))

const output = `// Generated by scripts/generate-vanilla-tables.ts. Do not edit by hand.\n` +
  `export const VANILLA_26_3_BIOME_IDS = ${JSON.stringify(Object.keys(climate), null, 2)} as const\n` +
  `export const VANILLA_26_3_BIOME_CLIMATE = ${JSON.stringify(climate, null, 2)} as const\n` +
  `export const VANILLA_26_3_DAMAGE_TYPE_IDS = ${JSON.stringify(damage, null, 2)} as const\n` +
  `export const VANILLA_26_3_MOB_EFFECT_IDS = ${JSON.stringify(effects, null, 2)} as const\n` +
  `export const VANILLA_26_3_ENCHANTMENT_IDS = ${JSON.stringify(Object.keys(maxLevels), null, 2)} as const\n` +
  `export const VANILLA_26_3_ENCHANTMENT_MAX_LEVELS = ${JSON.stringify(maxLevels, null, 2)} as const\n` +
  `export const VANILLA_26_3_TAG_IDS = ${JSON.stringify(Object.keys(tags), null, 2)} as const\n`

const outputPath = process.argv[2] === '--output' && process.argv[3] !== undefined
  ? process.argv[3]
  : join(process.cwd(), 'src', 'domain', 'vanilla-26-3-generated.ts')

await writeFile(outputPath, output, 'utf8')
